// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"

	time "time"

	uuid "github.com/google/uuid"
)

// MockBookingRepo is an autogenerated mock type for the BookingRepo type
type MockBookingRepo struct {
	mock.Mock
}

type MockBookingRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepo) EXPECT() *MockBookingRepo_Expecter {
	return &MockBookingRepo_Expecter{mock: &_m.Mock}
}

// CreateBooking provides a mock function with given fields: ctx, in
func (_m *MockBookingRepo) CreateBooking(ctx context.Context, in entity.BookSlotInput) (*entity.Booking, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 *entity.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.BookSlotInput) (*entity.Booking, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.BookSlotInput) *entity.Booking); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.BookSlotInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepo_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockBookingRepo_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.BookSlotInput
func (_e *MockBookingRepo_Expecter) CreateBooking(ctx interface{}, in interface{}) *MockBookingRepo_CreateBooking_Call {
	return &MockBookingRepo_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, in)}
}

func (_c *MockBookingRepo_CreateBooking_Call) Run(run func(ctx context.Context, in entity.BookSlotInput)) *MockBookingRepo_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.BookSlotInput))
	})
	return _c
}

func (_c *MockBookingRepo_CreateBooking_Call) Return(_a0 *entity.Booking, _a1 error) *MockBookingRepo_CreateBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepo_CreateBooking_Call) RunAndReturn(run func(context.Context, entity.BookSlotInput) (*entity.Booking, error)) *MockBookingRepo_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookedSlots provides a mock function with given fields: ctx, courtID, from, to
func (_m *MockBookingRepo) ListBookedSlots(ctx context.Context, courtID uuid.UUID, from time.Time, to time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, courtID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListBookedSlots")
	}

	var r0 []time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]time.Time, error)); ok {
		return rf(ctx, courtID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []time.Time); ok {
		r0 = rf(ctx, courtID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, courtID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepo_ListBookedSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookedSlots'
type MockBookingRepo_ListBookedSlots_Call struct {
	*mock.Call
}

// ListBookedSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - courtID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockBookingRepo_Expecter) ListBookedSlots(ctx interface{}, courtID interface{}, from interface{}, to interface{}) *MockBookingRepo_ListBookedSlots_Call {
	return &MockBookingRepo_ListBookedSlots_Call{Call: _e.mock.On("ListBookedSlots", ctx, courtID, from, to)}
}

func (_c *MockBookingRepo_ListBookedSlots_Call) Run(run func(ctx context.Context, courtID uuid.UUID, from time.Time, to time.Time)) *MockBookingRepo_ListBookedSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockBookingRepo_ListBookedSlots_Call) Return(_a0 []time.Time, _a1 error) *MockBookingRepo_ListBookedSlots_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepo_ListBookedSlots_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]time.Time, error)) *MockBookingRepo_ListBookedSlots_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlayerBookings provides a mock function with given fields: ctx, playerID, from
func (_m *MockBookingRepo) ListPlayerBookings(ctx context.Context, playerID uuid.UUID, from time.Time) ([]entity.PlayerBooking, error) {
	ret := _m.Called(ctx, playerID, from)

	if len(ret) == 0 {
		panic("no return value specified for ListPlayerBookings")
	}

	var r0 []entity.PlayerBooking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]entity.PlayerBooking, error)); ok {
		return rf(ctx, playerID, from)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []entity.PlayerBooking); ok {
		r0 = rf(ctx, playerID, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlayerBooking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, playerID, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepo_ListPlayerBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlayerBookings'
type MockBookingRepo_ListPlayerBookings_Call struct {
	*mock.Call
}

// ListPlayerBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - from time.Time
func (_e *MockBookingRepo_Expecter) ListPlayerBookings(ctx interface{}, playerID interface{}, from interface{}) *MockBookingRepo_ListPlayerBookings_Call {
	return &MockBookingRepo_ListPlayerBookings_Call{Call: _e.mock.On("ListPlayerBookings", ctx, playerID, from)}
}

func (_c *MockBookingRepo_ListPlayerBookings_Call) Run(run func(ctx context.Context, playerID uuid.UUID, from time.Time)) *MockBookingRepo_ListPlayerBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockBookingRepo_ListPlayerBookings_Call) Return(_a0 []entity.PlayerBooking, _a1 error) *MockBookingRepo_ListPlayerBookings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepo_ListPlayerBookings_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]entity.PlayerBooking, error)) *MockBookingRepo_ListPlayerBookings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingRepo creates a new instance of MockBookingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepo {
	mock := &MockBookingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
