// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"

	time "time"

	uuid "github.com/google/uuid"
)

// MockBookingRepo is an autogenerated mock type for the BookingRepo type
type MockBookingRepo struct {
	mock.Mock
}

type MockBookingRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepo) EXPECT() *MockBookingRepo_Expecter {
	return &MockBookingRepo_Expecter{mock: &_m.Mock}
}

// AttachPayment provides a mock function with given fields: ctx, bookingID, paymentIntentID
func (_m *MockBookingRepo) AttachPayment(ctx context.Context, bookingID uuid.UUID, paymentIntentID string) error {
	ret := _m.Called(ctx, bookingID, paymentIntentID)

	if len(ret) == 0 {
		panic("no return value specified for AttachPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, bookingID, paymentIntentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookingRepo_AttachPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachPayment'
type MockBookingRepo_AttachPayment_Call struct {
	*mock.Call
}

// AttachPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID uuid.UUID
//   - paymentIntentID string
func (_e *MockBookingRepo_Expecter) AttachPayment(ctx interface{}, bookingID interface{}, paymentIntentID interface{}) *MockBookingRepo_AttachPayment_Call {
	return &MockBookingRepo_AttachPayment_Call{Call: _e.mock.On("AttachPayment", ctx, bookingID, paymentIntentID)}
}

func (_c *MockBookingRepo_AttachPayment_Call) Run(run func(ctx context.Context, bookingID uuid.UUID, paymentIntentID string)) *MockBookingRepo_AttachPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockBookingRepo_AttachPayment_Call) Return(_a0 error) *MockBookingRepo_AttachPayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookingRepo_AttachPayment_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockBookingRepo_AttachPayment_Call {
	_c.Call.Return(run)
	return _c
}

// CancelBooking provides a mock function with given fields: ctx, bookingID
func (_m *MockBookingRepo) CancelBooking(ctx context.Context, bookingID uuid.UUID) error {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookingRepo_CancelBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBooking'
type MockBookingRepo_CancelBooking_Call struct {
	*mock.Call
}

// CancelBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID uuid.UUID
func (_e *MockBookingRepo_Expecter) CancelBooking(ctx interface{}, bookingID interface{}) *MockBookingRepo_CancelBooking_Call {
	return &MockBookingRepo_CancelBooking_Call{Call: _e.mock.On("CancelBooking", ctx, bookingID)}
}

func (_c *MockBookingRepo_CancelBooking_Call) Run(run func(ctx context.Context, bookingID uuid.UUID)) *MockBookingRepo_CancelBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingRepo_CancelBooking_Call) Return(_a0 error) *MockBookingRepo_CancelBooking_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookingRepo_CancelBooking_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockBookingRepo_CancelBooking_Call {
	_c.Call.Return(run)
	return _c
}

// HoldSlot provides a mock function with given fields: ctx, in, amount, holdExpiresAt
func (_m *MockBookingRepo) HoldSlot(ctx context.Context, in entity.BookSlotInput, amount int, holdExpiresAt time.Time) (*entity.Booking, error) {
	ret := _m.Called(ctx, in, amount, holdExpiresAt)

	if len(ret) == 0 {
		panic("no return value specified for HoldSlot")
	}

	var r0 *entity.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.BookSlotInput, int, time.Time) (*entity.Booking, error)); ok {
		return rf(ctx, in, amount, holdExpiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.BookSlotInput, int, time.Time) *entity.Booking); ok {
		r0 = rf(ctx, in, amount, holdExpiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.BookSlotInput, int, time.Time) error); ok {
		r1 = rf(ctx, in, amount, holdExpiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepo_HoldSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HoldSlot'
type MockBookingRepo_HoldSlot_Call struct {
	*mock.Call
}

// HoldSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.BookSlotInput
//   - amount int
//   - holdExpiresAt time.Time
func (_e *MockBookingRepo_Expecter) HoldSlot(ctx interface{}, in interface{}, amount interface{}, holdExpiresAt interface{}) *MockBookingRepo_HoldSlot_Call {
	return &MockBookingRepo_HoldSlot_Call{Call: _e.mock.On("HoldSlot", ctx, in, amount, holdExpiresAt)}
}

func (_c *MockBookingRepo_HoldSlot_Call) Run(run func(ctx context.Context, in entity.BookSlotInput, amount int, holdExpiresAt time.Time)) *MockBookingRepo_HoldSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.BookSlotInput), args[2].(int), args[3].(time.Time))
	})
	return _c
}

func (_c *MockBookingRepo_HoldSlot_Call) Return(_a0 *entity.Booking, _a1 error) *MockBookingRepo_HoldSlot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepo_HoldSlot_Call) RunAndReturn(run func(context.Context, entity.BookSlotInput, int, time.Time) (*entity.Booking, error)) *MockBookingRepo_HoldSlot_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookedSlots provides a mock function with given fields: ctx, courtID, from, to
func (_m *MockBookingRepo) ListBookedSlots(ctx context.Context, courtID uuid.UUID, from time.Time, to time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, courtID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListBookedSlots")
	}

	var r0 []time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]time.Time, error)); ok {
		return rf(ctx, courtID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []time.Time); ok {
		r0 = rf(ctx, courtID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, courtID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepo_ListBookedSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookedSlots'
type MockBookingRepo_ListBookedSlots_Call struct {
	*mock.Call
}

// ListBookedSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - courtID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockBookingRepo_Expecter) ListBookedSlots(ctx interface{}, courtID interface{}, from interface{}, to interface{}) *MockBookingRepo_ListBookedSlots_Call {
	return &MockBookingRepo_ListBookedSlots_Call{Call: _e.mock.On("ListBookedSlots", ctx, courtID, from, to)}
}

func (_c *MockBookingRepo_ListBookedSlots_Call) Run(run func(ctx context.Context, courtID uuid.UUID, from time.Time, to time.Time)) *MockBookingRepo_ListBookedSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockBookingRepo_ListBookedSlots_Call) Return(_a0 []time.Time, _a1 error) *MockBookingRepo_ListBookedSlots_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepo_ListBookedSlots_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]time.Time, error)) *MockBookingRepo_ListBookedSlots_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlayerBookings provides a mock function with given fields: ctx, playerID, from
func (_m *MockBookingRepo) ListPlayerBookings(ctx context.Context, playerID uuid.UUID, from time.Time) ([]entity.PlayerBooking, error) {
	ret := _m.Called(ctx, playerID, from)

	if len(ret) == 0 {
		panic("no return value specified for ListPlayerBookings")
	}

	var r0 []entity.PlayerBooking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]entity.PlayerBooking, error)); ok {
		return rf(ctx, playerID, from)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []entity.PlayerBooking); ok {
		r0 = rf(ctx, playerID, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlayerBooking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, playerID, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepo_ListPlayerBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlayerBookings'
type MockBookingRepo_ListPlayerBookings_Call struct {
	*mock.Call
}

// ListPlayerBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - from time.Time
func (_e *MockBookingRepo_Expecter) ListPlayerBookings(ctx interface{}, playerID interface{}, from interface{}) *MockBookingRepo_ListPlayerBookings_Call {
	return &MockBookingRepo_ListPlayerBookings_Call{Call: _e.mock.On("ListPlayerBookings", ctx, playerID, from)}
}

func (_c *MockBookingRepo_ListPlayerBookings_Call) Run(run func(ctx context.Context, playerID uuid.UUID, from time.Time)) *MockBookingRepo_ListPlayerBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockBookingRepo_ListPlayerBookings_Call) Return(_a0 []entity.PlayerBooking, _a1 error) *MockBookingRepo_ListPlayerBookings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepo_ListPlayerBookings_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]entity.PlayerBooking, error)) *MockBookingRepo_ListPlayerBookings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingRepo creates a new instance of MockBookingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepo {
	mock := &MockBookingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
