// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBookedSlotFinder is an autogenerated mock type for the BookedSlotFinder type
type MockBookedSlotFinder struct {
	mock.Mock
}

type MockBookedSlotFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookedSlotFinder) EXPECT() *MockBookedSlotFinder_Expecter {
	return &MockBookedSlotFinder_Expecter{mock: &_m.Mock}
}

// ListBookedSlotsForCourts provides a mock function with given fields: ctx, courtIDs, from, to
func (_m *MockBookedSlotFinder) ListBookedSlotsForCourts(ctx context.Context, courtIDs []uuid.UUID, from time.Time, to time.Time) (map[uuid.UUID][]time.Time, error) {
	ret := _m.Called(ctx, courtIDs, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListBookedSlotsForCourts")
	}

	var r0 map[uuid.UUID][]time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID, time.Time, time.Time) (map[uuid.UUID][]time.Time, error)); ok {
		return rf(ctx, courtIDs, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID, time.Time, time.Time) map[uuid.UUID][]time.Time); ok {
		r0 = rf(ctx, courtIDs, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, courtIDs, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookedSlotFinder_ListBookedSlotsForCourts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookedSlotsForCourts'
type MockBookedSlotFinder_ListBookedSlotsForCourts_Call struct {
	*mock.Call
}

// ListBookedSlotsForCourts is a helper method to define mock.On call
//   - ctx context.Context
//   - courtIDs []uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockBookedSlotFinder_Expecter) ListBookedSlotsForCourts(ctx interface{}, courtIDs interface{}, from interface{}, to interface{}) *MockBookedSlotFinder_ListBookedSlotsForCourts_Call {
	return &MockBookedSlotFinder_ListBookedSlotsForCourts_Call{Call: _e.mock.On("ListBookedSlotsForCourts", ctx, courtIDs, from, to)}
}

func (_c *MockBookedSlotFinder_ListBookedSlotsForCourts_Call) Run(run func(ctx context.Context, courtIDs []uuid.UUID, from time.Time, to time.Time)) *MockBookedSlotFinder_ListBookedSlotsForCourts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockBookedSlotFinder_ListBookedSlotsForCourts_Call) Return(_a0 map[uuid.UUID][]time.Time, _a1 error) *MockBookedSlotFinder_ListBookedSlotsForCourts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookedSlotFinder_ListBookedSlotsForCourts_Call) RunAndReturn(run func(context.Context, []uuid.UUID, time.Time, time.Time) (map[uuid.UUID][]time.Time, error)) *MockBookedSlotFinder_ListBookedSlotsForCourts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookedSlotFinder creates a new instance of MockBookedSlotFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookedSlotFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookedSlotFinder {
	mock := &MockBookedSlotFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
