// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"
)

// MockBookingRepo is an autogenerated mock type for the BookingRepo type
type MockBookingRepo struct {
	mock.Mock
}

type MockBookingRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepo) EXPECT() *MockBookingRepo_Expecter {
	return &MockBookingRepo_Expecter{mock: &_m.Mock}
}

// CreateBooking provides a mock function with given fields: ctx, in
func (_m *MockBookingRepo) CreateBooking(ctx context.Context, in entity.BookSlotInput) (*entity.Booking, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 *entity.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.BookSlotInput) (*entity.Booking, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.BookSlotInput) *entity.Booking); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.BookSlotInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepo_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockBookingRepo_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.BookSlotInput
func (_e *MockBookingRepo_Expecter) CreateBooking(ctx interface{}, in interface{}) *MockBookingRepo_CreateBooking_Call {
	return &MockBookingRepo_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, in)}
}

func (_c *MockBookingRepo_CreateBooking_Call) Run(run func(ctx context.Context, in entity.BookSlotInput)) *MockBookingRepo_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.BookSlotInput))
	})
	return _c
}

func (_c *MockBookingRepo_CreateBooking_Call) Return(_a0 *entity.Booking, _a1 error) *MockBookingRepo_CreateBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepo_CreateBooking_Call) RunAndReturn(run func(context.Context, entity.BookSlotInput) (*entity.Booking, error)) *MockBookingRepo_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingRepo creates a new instance of MockBookingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepo {
	mock := &MockBookingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
