// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"
)

// MockCityRepo is an autogenerated mock type for the CityRepo type
type MockCityRepo struct {
	mock.Mock
}

type MockCityRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCityRepo) EXPECT() *MockCityRepo_Expecter {
	return &MockCityRepo_Expecter{mock: &_m.Mock}
}

// ListCities provides a mock function with given fields: ctx
func (_m *MockCityRepo) ListCities(ctx context.Context) ([]entity.City, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCities")
	}

	var r0 []entity.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.City, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.City); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCityRepo_ListCities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCities'
type MockCityRepo_ListCities_Call struct {
	*mock.Call
}

// ListCities is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCityRepo_Expecter) ListCities(ctx interface{}) *MockCityRepo_ListCities_Call {
	return &MockCityRepo_ListCities_Call{Call: _e.mock.On("ListCities", ctx)}
}

func (_c *MockCityRepo_ListCities_Call) Run(run func(ctx context.Context)) *MockCityRepo_ListCities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCityRepo_ListCities_Call) Return(_a0 []entity.City, _a1 error) *MockCityRepo_ListCities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCityRepo_ListCities_Call) RunAndReturn(run func(context.Context) ([]entity.City, error)) *MockCityRepo_ListCities_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCityRepo creates a new instance of MockCityRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCityRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCityRepo {
	mock := &MockCityRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
