// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// MockCourtRepo is an autogenerated mock type for the CourtRepo type
type MockCourtRepo struct {
	mock.Mock
}

type MockCourtRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourtRepo) EXPECT() *MockCourtRepo_Expecter {
	return &MockCourtRepo_Expecter{mock: &_m.Mock}
}

// CreateCourt provides a mock function with given fields: ctx, in
func (_m *MockCourtRepo) CreateCourt(ctx context.Context, in entity.CreateCourtInput) (*entity.Court, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourt")
	}

	var r0 *entity.Court
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateCourtInput) (*entity.Court, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateCourtInput) *entity.Court); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Court)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateCourtInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourtRepo_CreateCourt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCourt'
type MockCourtRepo_CreateCourt_Call struct {
	*mock.Call
}

// CreateCourt is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.CreateCourtInput
func (_e *MockCourtRepo_Expecter) CreateCourt(ctx interface{}, in interface{}) *MockCourtRepo_CreateCourt_Call {
	return &MockCourtRepo_CreateCourt_Call{Call: _e.mock.On("CreateCourt", ctx, in)}
}

func (_c *MockCourtRepo_CreateCourt_Call) Run(run func(ctx context.Context, in entity.CreateCourtInput)) *MockCourtRepo_CreateCourt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CreateCourtInput))
	})
	return _c
}

func (_c *MockCourtRepo_CreateCourt_Call) Return(_a0 *entity.Court, _a1 error) *MockCourtRepo_CreateCourt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourtRepo_CreateCourt_Call) RunAndReturn(run func(context.Context, entity.CreateCourtInput) (*entity.Court, error)) *MockCourtRepo_CreateCourt_Call {
	_c.Call.Return(run)
	return _c
}

// ListCourtsByVenue provides a mock function with given fields: ctx, venueID
func (_m *MockCourtRepo) ListCourtsByVenue(ctx context.Context, venueID uuid.UUID) ([]entity.Court, error) {
	ret := _m.Called(ctx, venueID)

	if len(ret) == 0 {
		panic("no return value specified for ListCourtsByVenue")
	}

	var r0 []entity.Court
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Court, error)); ok {
		return rf(ctx, venueID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Court); ok {
		r0 = rf(ctx, venueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Court)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, venueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourtRepo_ListCourtsByVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCourtsByVenue'
type MockCourtRepo_ListCourtsByVenue_Call struct {
	*mock.Call
}

// ListCourtsByVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - venueID uuid.UUID
func (_e *MockCourtRepo_Expecter) ListCourtsByVenue(ctx interface{}, venueID interface{}) *MockCourtRepo_ListCourtsByVenue_Call {
	return &MockCourtRepo_ListCourtsByVenue_Call{Call: _e.mock.On("ListCourtsByVenue", ctx, venueID)}
}

func (_c *MockCourtRepo_ListCourtsByVenue_Call) Run(run func(ctx context.Context, venueID uuid.UUID)) *MockCourtRepo_ListCourtsByVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCourtRepo_ListCourtsByVenue_Call) Return(_a0 []entity.Court, _a1 error) *MockCourtRepo_ListCourtsByVenue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourtRepo_ListCourtsByVenue_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Court, error)) *MockCourtRepo_ListCourtsByVenue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourtRepo creates a new instance of MockCourtRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourtRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourtRepo {
	mock := &MockCourtRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
