// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// MockCourtFinder is an autogenerated mock type for the CourtFinder type
type MockCourtFinder struct {
	mock.Mock
}

type MockCourtFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourtFinder) EXPECT() *MockCourtFinder_Expecter {
	return &MockCourtFinder_Expecter{mock: &_m.Mock}
}

// GetCourtWithVenue provides a mock function with given fields: ctx, id
func (_m *MockCourtFinder) GetCourtWithVenue(ctx context.Context, id uuid.UUID) (*entity.Court, *entity.Venue, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCourtWithVenue")
	}

	var r0 *entity.Court
	var r1 *entity.Venue
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Court, *entity.Venue, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Court); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Court)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) *entity.Venue); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.Venue)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCourtFinder_GetCourtWithVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourtWithVenue'
type MockCourtFinder_GetCourtWithVenue_Call struct {
	*mock.Call
}

// GetCourtWithVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCourtFinder_Expecter) GetCourtWithVenue(ctx interface{}, id interface{}) *MockCourtFinder_GetCourtWithVenue_Call {
	return &MockCourtFinder_GetCourtWithVenue_Call{Call: _e.mock.On("GetCourtWithVenue", ctx, id)}
}

func (_c *MockCourtFinder_GetCourtWithVenue_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCourtFinder_GetCourtWithVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCourtFinder_GetCourtWithVenue_Call) Return(_a0 *entity.Court, _a1 *entity.Venue, _a2 error) *MockCourtFinder_GetCourtWithVenue_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCourtFinder_GetCourtWithVenue_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Court, *entity.Venue, error)) *MockCourtFinder_GetCourtWithVenue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourtFinder creates a new instance of MockCourtFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourtFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourtFinder {
	mock := &MockCourtFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
