// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCredentialFinder is an autogenerated mock type for the CredentialFinder type
type MockCredentialFinder struct {
	mock.Mock
}

type MockCredentialFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialFinder) EXPECT() *MockCredentialFinder_Expecter {
	return &MockCredentialFinder_Expecter{mock: &_m.Mock}
}

// GetCredentialsByEmail provides a mock function with given fields: ctx, email
func (_m *MockCredentialFinder) GetCredentialsByEmail(ctx context.Context, email string) (uuid.UUID, string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialsByEmail")
	}

	var r0 uuid.UUID
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCredentialFinder_GetCredentialsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialsByEmail'
type MockCredentialFinder_GetCredentialsByEmail_Call struct {
	*mock.Call
}

// GetCredentialsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockCredentialFinder_Expecter) GetCredentialsByEmail(ctx interface{}, email interface{}) *MockCredentialFinder_GetCredentialsByEmail_Call {
	return &MockCredentialFinder_GetCredentialsByEmail_Call{Call: _e.mock.On("GetCredentialsByEmail", ctx, email)}
}

func (_c *MockCredentialFinder_GetCredentialsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockCredentialFinder_GetCredentialsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCredentialFinder_GetCredentialsByEmail_Call) Return(userID uuid.UUID, passwordHash string, err error) *MockCredentialFinder_GetCredentialsByEmail_Call {
	_c.Call.Return(userID, passwordHash, err)
	return _c
}

func (_c *MockCredentialFinder_GetCredentialsByEmail_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, string, error)) *MockCredentialFinder_GetCredentialsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialFinder creates a new instance of MockCredentialFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialFinder {
	mock := &MockCredentialFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
