// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockHoldReleaser is an autogenerated mock type for the HoldReleaser type
type MockHoldReleaser struct {
	mock.Mock
}

type MockHoldReleaser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHoldReleaser) EXPECT() *MockHoldReleaser_Expecter {
	return &MockHoldReleaser_Expecter{mock: &_m.Mock}
}

// ReleaseLapsedHolds provides a mock function with given fields: ctx, asOf
func (_m *MockHoldReleaser) ReleaseLapsedHolds(ctx context.Context, asOf time.Time) (int, error) {
	ret := _m.Called(ctx, asOf)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseLapsedHolds")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return rf(ctx, asOf)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = rf(ctx, asOf)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, asOf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHoldReleaser_ReleaseLapsedHolds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseLapsedHolds'
type MockHoldReleaser_ReleaseLapsedHolds_Call struct {
	*mock.Call
}

// ReleaseLapsedHolds is a helper method to define mock.On call
//   - ctx context.Context
//   - asOf time.Time
func (_e *MockHoldReleaser_Expecter) ReleaseLapsedHolds(ctx interface{}, asOf interface{}) *MockHoldReleaser_ReleaseLapsedHolds_Call {
	return &MockHoldReleaser_ReleaseLapsedHolds_Call{Call: _e.mock.On("ReleaseLapsedHolds", ctx, asOf)}
}

func (_c *MockHoldReleaser_ReleaseLapsedHolds_Call) Run(run func(ctx context.Context, asOf time.Time)) *MockHoldReleaser_ReleaseLapsedHolds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockHoldReleaser_ReleaseLapsedHolds_Call) Return(_a0 int, _a1 error) *MockHoldReleaser_ReleaseLapsedHolds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHoldReleaser_ReleaseLapsedHolds_Call) RunAndReturn(run func(context.Context, time.Time) (int, error)) *MockHoldReleaser_ReleaseLapsedHolds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHoldReleaser creates a new instance of MockHoldReleaser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHoldReleaser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHoldReleaser {
	mock := &MockHoldReleaser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
