// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPasswordComparer is an autogenerated mock type for the PasswordComparer type
type MockPasswordComparer struct {
	mock.Mock
}

type MockPasswordComparer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordComparer) EXPECT() *MockPasswordComparer_Expecter {
	return &MockPasswordComparer_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function with given fields: hash, plain
func (_m *MockPasswordComparer) Compare(hash string, plain string) error {
	ret := _m.Called(hash, plain)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hash, plain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordComparer_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockPasswordComparer_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - plain string
func (_e *MockPasswordComparer_Expecter) Compare(hash interface{}, plain interface{}) *MockPasswordComparer_Compare_Call {
	return &MockPasswordComparer_Compare_Call{Call: _e.mock.On("Compare", hash, plain)}
}

func (_c *MockPasswordComparer_Compare_Call) Run(run func(hash string, plain string)) *MockPasswordComparer_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordComparer_Compare_Call) Return(_a0 error) *MockPasswordComparer_Compare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordComparer_Compare_Call) RunAndReturn(run func(string, string) error) *MockPasswordComparer_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordComparer creates a new instance of MockPasswordComparer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordComparer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordComparer {
	mock := &MockPasswordComparer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
