// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentEventLog is an autogenerated mock type for the PaymentEventLog type
type MockPaymentEventLog struct {
	mock.Mock
}

type MockPaymentEventLog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentEventLog) EXPECT() *MockPaymentEventLog_Expecter {
	return &MockPaymentEventLog_Expecter{mock: &_m.Mock}
}

// RecordEvent provides a mock function with given fields: ctx, id, eventType
func (_m *MockPaymentEventLog) RecordEvent(ctx context.Context, id string, eventType string) (bool, error) {
	ret := _m.Called(ctx, id, eventType)

	if len(ret) == 0 {
		panic("no return value specified for RecordEvent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, id, eventType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, id, eventType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentEventLog_RecordEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordEvent'
type MockPaymentEventLog_RecordEvent_Call struct {
	*mock.Call
}

// RecordEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - eventType string
func (_e *MockPaymentEventLog_Expecter) RecordEvent(ctx interface{}, id interface{}, eventType interface{}) *MockPaymentEventLog_RecordEvent_Call {
	return &MockPaymentEventLog_RecordEvent_Call{Call: _e.mock.On("RecordEvent", ctx, id, eventType)}
}

func (_c *MockPaymentEventLog_RecordEvent_Call) Run(run func(ctx context.Context, id string, eventType string)) *MockPaymentEventLog_RecordEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPaymentEventLog_RecordEvent_Call) Return(first bool, err error) *MockPaymentEventLog_RecordEvent_Call {
	_c.Call.Return(first, err)
	return _c
}

func (_c *MockPaymentEventLog_RecordEvent_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockPaymentEventLog_RecordEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentEventLog creates a new instance of MockPaymentEventLog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentEventLog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentEventLog {
	mock := &MockPaymentEventLog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
