// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"
)

// MockPaymentGateway is an autogenerated mock type for the PaymentGateway type
type MockPaymentGateway struct {
	mock.Mock
}

type MockPaymentGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentGateway) EXPECT() *MockPaymentGateway_Expecter {
	return &MockPaymentGateway_Expecter{mock: &_m.Mock}
}

// CreatePayment provides a mock function with given fields: ctx, in
func (_m *MockPaymentGateway) CreatePayment(ctx context.Context, in entity.PaymentRequest) (*entity.Payment, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *entity.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaymentRequest) (*entity.Payment, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaymentRequest) *entity.Payment); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.PaymentRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentGateway_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockPaymentGateway_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.PaymentRequest
func (_e *MockPaymentGateway_Expecter) CreatePayment(ctx interface{}, in interface{}) *MockPaymentGateway_CreatePayment_Call {
	return &MockPaymentGateway_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, in)}
}

func (_c *MockPaymentGateway_CreatePayment_Call) Run(run func(ctx context.Context, in entity.PaymentRequest)) *MockPaymentGateway_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.PaymentRequest))
	})
	return _c
}

func (_c *MockPaymentGateway_CreatePayment_Call) Return(_a0 *entity.Payment, _a1 error) *MockPaymentGateway_CreatePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentGateway_CreatePayment_Call) RunAndReturn(run func(context.Context, entity.PaymentRequest) (*entity.Payment, error)) *MockPaymentGateway_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// GetPayment provides a mock function with given fields: ctx, intentID
func (_m *MockPaymentGateway) GetPayment(ctx context.Context, intentID string) (*entity.Payment, error) {
	ret := _m.Called(ctx, intentID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 *entity.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Payment, error)); ok {
		return rf(ctx, intentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Payment); ok {
		r0 = rf(ctx, intentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, intentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentGateway_GetPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPayment'
type MockPaymentGateway_GetPayment_Call struct {
	*mock.Call
}

// GetPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - intentID string
func (_e *MockPaymentGateway_Expecter) GetPayment(ctx interface{}, intentID interface{}) *MockPaymentGateway_GetPayment_Call {
	return &MockPaymentGateway_GetPayment_Call{Call: _e.mock.On("GetPayment", ctx, intentID)}
}

func (_c *MockPaymentGateway_GetPayment_Call) Run(run func(ctx context.Context, intentID string)) *MockPaymentGateway_GetPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentGateway_GetPayment_Call) Return(_a0 *entity.Payment, _a1 error) *MockPaymentGateway_GetPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentGateway_GetPayment_Call) RunAndReturn(run func(context.Context, string) (*entity.Payment, error)) *MockPaymentGateway_GetPayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentGateway creates a new instance of MockPaymentGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentGateway {
	mock := &MockPaymentGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
