// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"
)

// MockSessionCache is an autogenerated mock type for the SessionCache type
type MockSessionCache struct {
	mock.Mock
}

type MockSessionCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionCache) EXPECT() *MockSessionCache_Expecter {
	return &MockSessionCache_Expecter{mock: &_m.Mock}
}

// DeleteSession provides a mock function with given fields: ctx, tokenHash
func (_m *MockSessionCache) DeleteSession(ctx context.Context, tokenHash string) {
	_m.Called(ctx, tokenHash)
}

// MockSessionCache_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionCache_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockSessionCache_Expecter) DeleteSession(ctx interface{}, tokenHash interface{}) *MockSessionCache_DeleteSession_Call {
	return &MockSessionCache_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, tokenHash)}
}

func (_c *MockSessionCache_DeleteSession_Call) Run(run func(ctx context.Context, tokenHash string)) *MockSessionCache_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionCache_DeleteSession_Call) Return() *MockSessionCache_DeleteSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionCache_DeleteSession_Call) RunAndReturn(run func(context.Context, string)) *MockSessionCache_DeleteSession_Call {
	_c.Run(run)
	return _c
}

// GetSessionUser provides a mock function with given fields: ctx, tokenHash
func (_m *MockSessionCache) GetSessionUser(ctx context.Context, tokenHash string) (*entity.Session, *entity.User, bool) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionUser")
	}

	var r0 *entity.Session
	var r1 *entity.User
	var r2 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Session, *entity.User, bool)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Session); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *entity.User); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) bool); ok {
		r2 = rf(ctx, tokenHash)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockSessionCache_GetSessionUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionUser'
type MockSessionCache_GetSessionUser_Call struct {
	*mock.Call
}

// GetSessionUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockSessionCache_Expecter) GetSessionUser(ctx interface{}, tokenHash interface{}) *MockSessionCache_GetSessionUser_Call {
	return &MockSessionCache_GetSessionUser_Call{Call: _e.mock.On("GetSessionUser", ctx, tokenHash)}
}

func (_c *MockSessionCache_GetSessionUser_Call) Run(run func(ctx context.Context, tokenHash string)) *MockSessionCache_GetSessionUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionCache_GetSessionUser_Call) Return(_a0 *entity.Session, _a1 *entity.User, _a2 bool) *MockSessionCache_GetSessionUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSessionCache_GetSessionUser_Call) RunAndReturn(run func(context.Context, string) (*entity.Session, *entity.User, bool)) *MockSessionCache_GetSessionUser_Call {
	_c.Call.Return(run)
	return _c
}

// PutSessionUser provides a mock function with given fields: ctx, tokenHash, session, user
func (_m *MockSessionCache) PutSessionUser(ctx context.Context, tokenHash string, session *entity.Session, user *entity.User) {
	_m.Called(ctx, tokenHash, session, user)
}

// MockSessionCache_PutSessionUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutSessionUser'
type MockSessionCache_PutSessionUser_Call struct {
	*mock.Call
}

// PutSessionUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - session *entity.Session
//   - user *entity.User
func (_e *MockSessionCache_Expecter) PutSessionUser(ctx interface{}, tokenHash interface{}, session interface{}, user interface{}) *MockSessionCache_PutSessionUser_Call {
	return &MockSessionCache_PutSessionUser_Call{Call: _e.mock.On("PutSessionUser", ctx, tokenHash, session, user)}
}

func (_c *MockSessionCache_PutSessionUser_Call) Run(run func(ctx context.Context, tokenHash string, session *entity.Session, user *entity.User)) *MockSessionCache_PutSessionUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*entity.Session), args[3].(*entity.User))
	})
	return _c
}

func (_c *MockSessionCache_PutSessionUser_Call) Return() *MockSessionCache_PutSessionUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionCache_PutSessionUser_Call) RunAndReturn(run func(context.Context, string, *entity.Session, *entity.User)) *MockSessionCache_PutSessionUser_Call {
	_c.Run(run)
	return _c
}

// NewMockSessionCache creates a new instance of MockSessionCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionCache {
	mock := &MockSessionCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
