// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, s, tokenHash
func (_m *MockSessionStore) CreateSession(ctx context.Context, s entity.Session, tokenHash string) (*entity.Session, error) {
	ret := _m.Called(ctx, s, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *entity.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Session, string) (*entity.Session, error)); ok {
		return rf(ctx, s, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Session, string) *entity.Session); ok {
		r0 = rf(ctx, s, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Session, string) error); ok {
		r1 = rf(ctx, s, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionStore_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - s entity.Session
//   - tokenHash string
func (_e *MockSessionStore_Expecter) CreateSession(ctx interface{}, s interface{}, tokenHash interface{}) *MockSessionStore_CreateSession_Call {
	return &MockSessionStore_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, s, tokenHash)}
}

func (_c *MockSessionStore_CreateSession_Call) Run(run func(ctx context.Context, s entity.Session, tokenHash string)) *MockSessionStore_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Session), args[2].(string))
	})
	return _c
}

func (_c *MockSessionStore_CreateSession_Call) Return(_a0 *entity.Session, _a1 error) *MockSessionStore_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_CreateSession_Call) RunAndReturn(run func(context.Context, entity.Session, string) (*entity.Session, error)) *MockSessionStore_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx, tokenHash
func (_m *MockSessionStore) DeleteSession(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionStore_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockSessionStore_Expecter) DeleteSession(ctx interface{}, tokenHash interface{}) *MockSessionStore_DeleteSession_Call {
	return &MockSessionStore_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, tokenHash)}
}

func (_c *MockSessionStore_DeleteSession_Call) Run(run func(ctx context.Context, tokenHash string)) *MockSessionStore_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_DeleteSession_Call) Return(_a0 error) *MockSessionStore_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_DeleteSession_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionStore_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionUser provides a mock function with given fields: ctx, tokenHash
func (_m *MockSessionStore) GetSessionUser(ctx context.Context, tokenHash string) (*entity.Session, *entity.User, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionUser")
	}

	var r0 *entity.Session
	var r1 *entity.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Session, *entity.User, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Session); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *entity.User); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, tokenHash)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSessionStore_GetSessionUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionUser'
type MockSessionStore_GetSessionUser_Call struct {
	*mock.Call
}

// GetSessionUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockSessionStore_Expecter) GetSessionUser(ctx interface{}, tokenHash interface{}) *MockSessionStore_GetSessionUser_Call {
	return &MockSessionStore_GetSessionUser_Call{Call: _e.mock.On("GetSessionUser", ctx, tokenHash)}
}

func (_c *MockSessionStore_GetSessionUser_Call) Run(run func(ctx context.Context, tokenHash string)) *MockSessionStore_GetSessionUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_GetSessionUser_Call) Return(_a0 *entity.Session, _a1 *entity.User, _a2 error) *MockSessionStore_GetSessionUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSessionStore_GetSessionUser_Call) RunAndReturn(run func(context.Context, string) (*entity.Session, *entity.User, error)) *MockSessionStore_GetSessionUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
