// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// MockUserFinder is an autogenerated mock type for the UserFinder type
type MockUserFinder struct {
	mock.Mock
}

type MockUserFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserFinder) EXPECT() *MockUserFinder_Expecter {
	return &MockUserFinder_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *MockUserFinder) GetUser(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFinder_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserFinder_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserFinder_Expecter) GetUser(ctx interface{}, id interface{}) *MockUserFinder_GetUser_Call {
	return &MockUserFinder_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUserFinder_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserFinder_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserFinder_GetUser_Call) Return(_a0 *entity.User, _a1 error) *MockUserFinder_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFinder_GetUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.User, error)) *MockUserFinder_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserFinder creates a new instance of MockUserFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserFinder {
	mock := &MockUserFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
