// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// MockVenueRepo is an autogenerated mock type for the VenueRepo type
type MockVenueRepo struct {
	mock.Mock
}

type MockVenueRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVenueRepo) EXPECT() *MockVenueRepo_Expecter {
	return &MockVenueRepo_Expecter{mock: &_m.Mock}
}

// CreateVenue provides a mock function with given fields: ctx, in
func (_m *MockVenueRepo) CreateVenue(ctx context.Context, in entity.CreateVenueInput) (*entity.Venue, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateVenue")
	}

	var r0 *entity.Venue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateVenueInput) (*entity.Venue, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateVenueInput) *entity.Venue); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Venue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateVenueInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVenueRepo_CreateVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVenue'
type MockVenueRepo_CreateVenue_Call struct {
	*mock.Call
}

// CreateVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.CreateVenueInput
func (_e *MockVenueRepo_Expecter) CreateVenue(ctx interface{}, in interface{}) *MockVenueRepo_CreateVenue_Call {
	return &MockVenueRepo_CreateVenue_Call{Call: _e.mock.On("CreateVenue", ctx, in)}
}

func (_c *MockVenueRepo_CreateVenue_Call) Run(run func(ctx context.Context, in entity.CreateVenueInput)) *MockVenueRepo_CreateVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CreateVenueInput))
	})
	return _c
}

func (_c *MockVenueRepo_CreateVenue_Call) Return(_a0 *entity.Venue, _a1 error) *MockVenueRepo_CreateVenue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVenueRepo_CreateVenue_Call) RunAndReturn(run func(context.Context, entity.CreateVenueInput) (*entity.Venue, error)) *MockVenueRepo_CreateVenue_Call {
	_c.Call.Return(run)
	return _c
}

// ListVenuesByOwner provides a mock function with given fields: ctx, ownerID
func (_m *MockVenueRepo) ListVenuesByOwner(ctx context.Context, ownerID uuid.UUID) ([]entity.Venue, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListVenuesByOwner")
	}

	var r0 []entity.Venue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Venue, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Venue); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Venue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVenueRepo_ListVenuesByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVenuesByOwner'
type MockVenueRepo_ListVenuesByOwner_Call struct {
	*mock.Call
}

// ListVenuesByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
func (_e *MockVenueRepo_Expecter) ListVenuesByOwner(ctx interface{}, ownerID interface{}) *MockVenueRepo_ListVenuesByOwner_Call {
	return &MockVenueRepo_ListVenuesByOwner_Call{Call: _e.mock.On("ListVenuesByOwner", ctx, ownerID)}
}

func (_c *MockVenueRepo_ListVenuesByOwner_Call) Run(run func(ctx context.Context, ownerID uuid.UUID)) *MockVenueRepo_ListVenuesByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVenueRepo_ListVenuesByOwner_Call) Return(_a0 []entity.Venue, _a1 error) *MockVenueRepo_ListVenuesByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVenueRepo_ListVenuesByOwner_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Venue, error)) *MockVenueRepo_ListVenuesByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVenueRepo creates a new instance of MockVenueRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVenueRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVenueRepo {
	mock := &MockVenueRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
