// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// MockVenueFinder is an autogenerated mock type for the VenueFinder type
type MockVenueFinder struct {
	mock.Mock
}

type MockVenueFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVenueFinder) EXPECT() *MockVenueFinder_Expecter {
	return &MockVenueFinder_Expecter{mock: &_m.Mock}
}

// GetVenue provides a mock function with given fields: ctx, id
func (_m *MockVenueFinder) GetVenue(ctx context.Context, id uuid.UUID) (*entity.Venue, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVenue")
	}

	var r0 *entity.Venue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Venue, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Venue); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Venue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVenueFinder_GetVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVenue'
type MockVenueFinder_GetVenue_Call struct {
	*mock.Call
}

// GetVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVenueFinder_Expecter) GetVenue(ctx interface{}, id interface{}) *MockVenueFinder_GetVenue_Call {
	return &MockVenueFinder_GetVenue_Call{Call: _e.mock.On("GetVenue", ctx, id)}
}

func (_c *MockVenueFinder_GetVenue_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVenueFinder_GetVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVenueFinder_GetVenue_Call) Return(_a0 *entity.Venue, _a1 error) *MockVenueFinder_GetVenue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVenueFinder_GetVenue_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Venue, error)) *MockVenueFinder_GetVenue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVenueFinder creates a new instance of MockVenueFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVenueFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVenueFinder {
	mock := &MockVenueFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
