// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"

	uuid "github.com/google/uuid"
)

// MockVenueLister is an autogenerated mock type for the VenueLister type
type MockVenueLister struct {
	mock.Mock
}

type MockVenueLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVenueLister) EXPECT() *MockVenueLister_Expecter {
	return &MockVenueLister_Expecter{mock: &_m.Mock}
}

// ListVenuesByOwner provides a mock function with given fields: ctx, ownerID
func (_m *MockVenueLister) ListVenuesByOwner(ctx context.Context, ownerID uuid.UUID) ([]entity.Venue, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListVenuesByOwner")
	}

	var r0 []entity.Venue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Venue, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Venue); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Venue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVenueLister_ListVenuesByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVenuesByOwner'
type MockVenueLister_ListVenuesByOwner_Call struct {
	*mock.Call
}

// ListVenuesByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
func (_e *MockVenueLister_Expecter) ListVenuesByOwner(ctx interface{}, ownerID interface{}) *MockVenueLister_ListVenuesByOwner_Call {
	return &MockVenueLister_ListVenuesByOwner_Call{Call: _e.mock.On("ListVenuesByOwner", ctx, ownerID)}
}

func (_c *MockVenueLister_ListVenuesByOwner_Call) Run(run func(ctx context.Context, ownerID uuid.UUID)) *MockVenueLister_ListVenuesByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVenueLister_ListVenuesByOwner_Call) Return(_a0 []entity.Venue, _a1 error) *MockVenueLister_ListVenuesByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVenueLister_ListVenuesByOwner_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Venue, error)) *MockVenueLister_ListVenuesByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVenueLister creates a new instance of MockVenueLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVenueLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVenueLister {
	mock := &MockVenueLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
