// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/thelong0705/deuce/internal/domain/entity"
)

// MockVenueCreator is an autogenerated mock type for the VenueCreator type
type MockVenueCreator struct {
	mock.Mock
}

type MockVenueCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVenueCreator) EXPECT() *MockVenueCreator_Expecter {
	return &MockVenueCreator_Expecter{mock: &_m.Mock}
}

// CreateVenue provides a mock function with given fields: ctx, in
func (_m *MockVenueCreator) CreateVenue(ctx context.Context, in entity.CreateVenueInput) (*entity.Venue, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateVenue")
	}

	var r0 *entity.Venue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateVenueInput) (*entity.Venue, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateVenueInput) *entity.Venue); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Venue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateVenueInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVenueCreator_CreateVenue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVenue'
type MockVenueCreator_CreateVenue_Call struct {
	*mock.Call
}

// CreateVenue is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.CreateVenueInput
func (_e *MockVenueCreator_Expecter) CreateVenue(ctx interface{}, in interface{}) *MockVenueCreator_CreateVenue_Call {
	return &MockVenueCreator_CreateVenue_Call{Call: _e.mock.On("CreateVenue", ctx, in)}
}

func (_c *MockVenueCreator_CreateVenue_Call) Run(run func(ctx context.Context, in entity.CreateVenueInput)) *MockVenueCreator_CreateVenue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CreateVenueInput))
	})
	return _c
}

func (_c *MockVenueCreator_CreateVenue_Call) Return(_a0 *entity.Venue, _a1 error) *MockVenueCreator_CreateVenue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVenueCreator_CreateVenue_Call) RunAndReturn(run func(context.Context, entity.CreateVenueInput) (*entity.Venue, error)) *MockVenueCreator_CreateVenue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVenueCreator creates a new instance of MockVenueCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVenueCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVenueCreator {
	mock := &MockVenueCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
