// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachPayment = `-- name: AttachPayment :exec
UPDATE bookings
SET payment_intent_id = $2
WHERE id = $1
`

type AttachPaymentParams struct {
	ID              uuid.UUID   `json:"id"`
	PaymentIntentID pgtype.Text `json:"payment_intent_id"`
}

func (q *Queries) AttachPayment(ctx context.Context, arg AttachPaymentParams) error {
	_, err := q.db.Exec(ctx, attachPayment, arg.ID, arg.PaymentIntentID)
	return err
}

const cancelBooking = `-- name: CancelBooking :exec
UPDATE bookings
SET cancelled_at = now()
WHERE id = $1 AND cancelled_at IS NULL
`

func (q *Queries) CancelBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelBooking, id)
	return err
}

const confirmBooking = `-- name: ConfirmBooking :exec
UPDATE bookings
SET status = 'confirmed', hold_expires_at = NULL
WHERE id = $1
`

func (q *Queries) ConfirmBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmBooking, id)
	return err
}

const getBooking = `-- name: GetBooking :one
SELECT id, court_id, player_id, is_block, starts_at, cancelled_at, created_at, updated_at, status, amount, hold_expires_at, payment_intent_id FROM bookings
WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CourtID,
		&i.PlayerID,
		&i.IsBlock,
		&i.StartsAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Amount,
		&i.HoldExpiresAt,
		&i.PaymentIntentID,
	)
	return i, err
}

const getBookingByPayment = `-- name: GetBookingByPayment :one
SELECT id, court_id, player_id, is_block, starts_at, cancelled_at, created_at, updated_at, status, amount, hold_expires_at, payment_intent_id FROM bookings
WHERE payment_intent_id = $1
`

func (q *Queries) GetBookingByPayment(ctx context.Context, paymentIntentID pgtype.Text) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByPayment, paymentIntentID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CourtID,
		&i.PlayerID,
		&i.IsBlock,
		&i.StartsAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Amount,
		&i.HoldExpiresAt,
		&i.PaymentIntentID,
	)
	return i, err
}

const getCourtVenue = `-- name: GetCourtVenue :one
SELECT courts.id, courts.venue_id, courts.name, courts.open_hour, courts.close_hour, courts.price_per_hour, courts.is_active, courts.created_at, courts.updated_at, courts.currency, venues.id, venues.owner_id, venues.name, venues.city, venues.address, venues.is_active, venues.created_at, venues.updated_at, venues.timezone
FROM courts
JOIN venues ON venues.id = courts.venue_id
WHERE courts.id = $1
`

type GetCourtVenueRow struct {
	Court Court `json:"court"`
	Venue Venue `json:"venue"`
}

func (q *Queries) GetCourtVenue(ctx context.Context, id uuid.UUID) (GetCourtVenueRow, error) {
	row := q.db.QueryRow(ctx, getCourtVenue, id)
	var i GetCourtVenueRow
	err := row.Scan(
		&i.Court.ID,
		&i.Court.VenueID,
		&i.Court.Name,
		&i.Court.OpenHour,
		&i.Court.CloseHour,
		&i.Court.PricePerHour,
		&i.Court.IsActive,
		&i.Court.CreatedAt,
		&i.Court.UpdatedAt,
		&i.Court.Currency,
		&i.Venue.ID,
		&i.Venue.OwnerID,
		&i.Venue.Name,
		&i.Venue.City,
		&i.Venue.Address,
		&i.Venue.IsActive,
		&i.Venue.CreatedAt,
		&i.Venue.UpdatedAt,
		&i.Venue.Timezone,
	)
	return i, err
}

const holdSlot = `-- name: HoldSlot :one
INSERT INTO bookings (
    court_id, player_id, starts_at, status, amount, hold_expires_at
) VALUES (
    $1, $2, $3, 'pending_payment', $4, $5
)
RETURNING id, court_id, player_id, is_block, starts_at, cancelled_at, created_at, updated_at, status, amount, hold_expires_at, payment_intent_id
`

type HoldSlotParams struct {
	CourtID       uuid.UUID          `json:"court_id"`
	PlayerID      uuid.NullUUID      `json:"player_id"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	Amount        pgtype.Int4        `json:"amount"`
	HoldExpiresAt pgtype.Timestamptz `json:"hold_expires_at"`
}

func (q *Queries) HoldSlot(ctx context.Context, arg HoldSlotParams) (Booking, error) {
	row := q.db.QueryRow(ctx, holdSlot,
		arg.CourtID,
		arg.PlayerID,
		arg.StartsAt,
		arg.Amount,
		arg.HoldExpiresAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CourtID,
		&i.PlayerID,
		&i.IsBlock,
		&i.StartsAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Amount,
		&i.HoldExpiresAt,
		&i.PaymentIntentID,
	)
	return i, err
}

const listBookedSlots = `-- name: ListBookedSlots :many
SELECT starts_at FROM bookings
WHERE court_id = $1
  AND cancelled_at IS NULL
  AND starts_at >= $2
  AND starts_at < $3
ORDER BY starts_at
`

type ListBookedSlotsParams struct {
	CourtID    uuid.UUID          `json:"court_id"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	StartsAt_2 pgtype.Timestamptz `json:"starts_at_2"`
}

func (q *Queries) ListBookedSlots(ctx context.Context, arg ListBookedSlotsParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, listBookedSlots, arg.CourtID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Timestamptz{}
	for rows.Next() {
		var starts_at pgtype.Timestamptz
		if err := rows.Scan(&starts_at); err != nil {
			return nil, err
		}
		items = append(items, starts_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookedSlotsForCourts = `-- name: ListBookedSlotsForCourts :many
SELECT court_id, starts_at FROM bookings
WHERE court_id = ANY($1::uuid[])
  AND cancelled_at IS NULL
  AND starts_at >= $2
  AND starts_at < $3
ORDER BY court_id, starts_at
`

type ListBookedSlotsForCourtsParams struct {
	CourtIds []uuid.UUID        `json:"court_ids"`
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type ListBookedSlotsForCourtsRow struct {
	CourtID  uuid.UUID          `json:"court_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) ListBookedSlotsForCourts(ctx context.Context, arg ListBookedSlotsForCourtsParams) ([]ListBookedSlotsForCourtsRow, error) {
	rows, err := q.db.Query(ctx, listBookedSlotsForCourts, arg.CourtIds, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookedSlotsForCourtsRow{}
	for rows.Next() {
		var i ListBookedSlotsForCourtsRow
		if err := rows.Scan(&i.CourtID, &i.StartsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerBookings = `-- name: ListPlayerBookings :many
SELECT bookings.id, bookings.court_id, bookings.player_id, bookings.is_block, bookings.starts_at, bookings.cancelled_at, bookings.created_at, bookings.updated_at, bookings.status, bookings.amount, bookings.hold_expires_at, bookings.payment_intent_id, courts.id, courts.venue_id, courts.name, courts.open_hour, courts.close_hour, courts.price_per_hour, courts.is_active, courts.created_at, courts.updated_at, courts.currency, venues.id, venues.owner_id, venues.name, venues.city, venues.address, venues.is_active, venues.created_at, venues.updated_at, venues.timezone
FROM bookings
JOIN courts ON courts.id = bookings.court_id
JOIN venues ON venues.id = courts.venue_id
WHERE bookings.player_id = $1
  AND bookings.cancelled_at IS NULL
  AND bookings.starts_at >= $2
ORDER BY bookings.starts_at
`

type ListPlayerBookingsParams struct {
	PlayerID uuid.NullUUID      `json:"player_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

type ListPlayerBookingsRow struct {
	Booking Booking `json:"booking"`
	Court   Court   `json:"court"`
	Venue   Venue   `json:"venue"`
}

func (q *Queries) ListPlayerBookings(ctx context.Context, arg ListPlayerBookingsParams) ([]ListPlayerBookingsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerBookings, arg.PlayerID, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerBookingsRow{}
	for rows.Next() {
		var i ListPlayerBookingsRow
		if err := rows.Scan(
			&i.Booking.ID,
			&i.Booking.CourtID,
			&i.Booking.PlayerID,
			&i.Booking.IsBlock,
			&i.Booking.StartsAt,
			&i.Booking.CancelledAt,
			&i.Booking.CreatedAt,
			&i.Booking.UpdatedAt,
			&i.Booking.Status,
			&i.Booking.Amount,
			&i.Booking.HoldExpiresAt,
			&i.Booking.PaymentIntentID,
			&i.Court.ID,
			&i.Court.VenueID,
			&i.Court.Name,
			&i.Court.OpenHour,
			&i.Court.CloseHour,
			&i.Court.PricePerHour,
			&i.Court.IsActive,
			&i.Court.CreatedAt,
			&i.Court.UpdatedAt,
			&i.Court.Currency,
			&i.Venue.ID,
			&i.Venue.OwnerID,
			&i.Venue.Name,
			&i.Venue.City,
			&i.Venue.Address,
			&i.Venue.IsActive,
			&i.Venue.CreatedAt,
			&i.Venue.UpdatedAt,
			&i.Venue.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseLapsedHolds = `-- name: ReleaseLapsedHolds :execrows
UPDATE bookings
SET cancelled_at = now()
WHERE status = 'pending_payment'
  AND cancelled_at IS NULL
  AND hold_expires_at <= $1
`

func (q *Queries) ReleaseLapsedHolds(ctx context.Context, holdExpiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, releaseLapsedHolds, holdExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
