// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    court_id, player_id, starts_at
) VALUES (
    $1, $2, $3
)
RETURNING id, court_id, player_id, is_block, starts_at, cancelled_at, created_at, updated_at
`

type CreateBookingParams struct {
	CourtID  uuid.UUID          `json:"court_id"`
	PlayerID uuid.NullUUID      `json:"player_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.CourtID, arg.PlayerID, arg.StartsAt)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CourtID,
		&i.PlayerID,
		&i.IsBlock,
		&i.StartsAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourtVenue = `-- name: GetCourtVenue :one
SELECT courts.id, courts.venue_id, courts.name, courts.open_hour, courts.close_hour, courts.price_per_hour, courts.is_active, courts.created_at, courts.updated_at, venues.id, venues.owner_id, venues.name, venues.city, venues.address, venues.is_active, venues.created_at, venues.updated_at, venues.timezone
FROM courts
JOIN venues ON venues.id = courts.venue_id
WHERE courts.id = $1
`

type GetCourtVenueRow struct {
	Court Court `json:"court"`
	Venue Venue `json:"venue"`
}

func (q *Queries) GetCourtVenue(ctx context.Context, id uuid.UUID) (GetCourtVenueRow, error) {
	row := q.db.QueryRow(ctx, getCourtVenue, id)
	var i GetCourtVenueRow
	err := row.Scan(
		&i.Court.ID,
		&i.Court.VenueID,
		&i.Court.Name,
		&i.Court.OpenHour,
		&i.Court.CloseHour,
		&i.Court.PricePerHour,
		&i.Court.IsActive,
		&i.Court.CreatedAt,
		&i.Court.UpdatedAt,
		&i.Venue.ID,
		&i.Venue.OwnerID,
		&i.Venue.Name,
		&i.Venue.City,
		&i.Venue.Address,
		&i.Venue.IsActive,
		&i.Venue.CreatedAt,
		&i.Venue.UpdatedAt,
		&i.Venue.Timezone,
	)
	return i, err
}
