// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city.sql

package postgres

import (
	"context"
)

const listCities = `-- name: ListCities :many
SELECT name, timezone FROM cities
ORDER BY name
`

func (q *Queries) ListCities(ctx context.Context) ([]City, error) {
	rows, err := q.db.Query(ctx, listCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(&i.Name, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
