// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: court.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createCourt = `-- name: CreateCourt :one
INSERT INTO courts (
    venue_id, name, open_hour, close_hour, price_per_hour
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, venue_id, name, open_hour, close_hour, price_per_hour, is_active, created_at, updated_at
`

type CreateCourtParams struct {
	VenueID      uuid.UUID `json:"venue_id"`
	Name         string    `json:"name"`
	OpenHour     int16     `json:"open_hour"`
	CloseHour    int16     `json:"close_hour"`
	PricePerHour int32     `json:"price_per_hour"`
}

func (q *Queries) CreateCourt(ctx context.Context, arg CreateCourtParams) (Court, error) {
	row := q.db.QueryRow(ctx, createCourt,
		arg.VenueID,
		arg.Name,
		arg.OpenHour,
		arg.CloseHour,
		arg.PricePerHour,
	)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.OpenHour,
		&i.CloseHour,
		&i.PricePerHour,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourtsByVenue = `-- name: ListCourtsByVenue :many
SELECT id, venue_id, name, open_hour, close_hour, price_per_hour, is_active, created_at, updated_at FROM courts
WHERE venue_id = $1 AND is_active
ORDER BY name
`

func (q *Queries) ListCourtsByVenue(ctx context.Context, venueID uuid.UUID) ([]Court, error) {
	rows, err := q.db.Query(ctx, listCourtsByVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Court{}
	for rows.Next() {
		var i Court
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.Name,
			&i.OpenHour,
			&i.CloseHour,
			&i.PricePerHour,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCourts = `-- name: SearchCourts :many
SELECT courts.id, courts.venue_id, courts.name, courts.open_hour, courts.close_hour, courts.price_per_hour, courts.is_active, courts.created_at, courts.updated_at, venues.id, venues.owner_id, venues.name, venues.city, venues.address, venues.is_active, venues.created_at, venues.updated_at, venues.timezone
FROM courts
JOIN venues ON venues.id = courts.venue_id
WHERE venues.city = $1
  AND venues.is_active
  AND courts.is_active
ORDER BY venues.name, courts.name
`

type SearchCourtsRow struct {
	Court Court `json:"court"`
	Venue Venue `json:"venue"`
}

func (q *Queries) SearchCourts(ctx context.Context, city string) ([]SearchCourtsRow, error) {
	rows, err := q.db.Query(ctx, searchCourts, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCourtsRow{}
	for rows.Next() {
		var i SearchCourtsRow
		if err := rows.Scan(
			&i.Court.ID,
			&i.Court.VenueID,
			&i.Court.Name,
			&i.Court.OpenHour,
			&i.Court.CloseHour,
			&i.Court.PricePerHour,
			&i.Court.IsActive,
			&i.Court.CreatedAt,
			&i.Court.UpdatedAt,
			&i.Venue.ID,
			&i.Venue.OwnerID,
			&i.Venue.Name,
			&i.Venue.City,
			&i.Venue.Address,
			&i.Venue.IsActive,
			&i.Venue.CreatedAt,
			&i.Venue.UpdatedAt,
			&i.Venue.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
