// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: court.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createCourt = `-- name: CreateCourt :one
INSERT INTO courts (
    venue_id, name, open_hour, close_hour, price_per_hour
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, venue_id, name, open_hour, close_hour, price_per_hour, is_active, created_at, updated_at
`

type CreateCourtParams struct {
	VenueID      uuid.UUID `json:"venue_id"`
	Name         string    `json:"name"`
	OpenHour     int16     `json:"open_hour"`
	CloseHour    int16     `json:"close_hour"`
	PricePerHour int32     `json:"price_per_hour"`
}

func (q *Queries) CreateCourt(ctx context.Context, arg CreateCourtParams) (Court, error) {
	row := q.db.QueryRow(ctx, createCourt,
		arg.VenueID,
		arg.Name,
		arg.OpenHour,
		arg.CloseHour,
		arg.PricePerHour,
	)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.OpenHour,
		&i.CloseHour,
		&i.PricePerHour,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourtsByVenue = `-- name: ListCourtsByVenue :many
SELECT id, venue_id, name, open_hour, close_hour, price_per_hour, is_active, created_at, updated_at FROM courts
WHERE venue_id = $1 AND is_active
ORDER BY name
`

func (q *Queries) ListCourtsByVenue(ctx context.Context, venueID uuid.UUID) ([]Court, error) {
	rows, err := q.db.Query(ctx, listCourtsByVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Court{}
	for rows.Next() {
		var i Court
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.Name,
			&i.OpenHour,
			&i.CloseHour,
			&i.PricePerHour,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
