// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: court.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createCourt = `-- name: CreateCourt :one
INSERT INTO courts (
    venue_id, name, open_hour, close_hour, price_per_hour
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, venue_id, name, open_hour, close_hour, price_per_hour, is_active, created_at, updated_at
`

type CreateCourtParams struct {
	VenueID      uuid.UUID `json:"venue_id"`
	Name         string    `json:"name"`
	OpenHour     int16     `json:"open_hour"`
	CloseHour    int16     `json:"close_hour"`
	PricePerHour int32     `json:"price_per_hour"`
}

func (q *Queries) CreateCourt(ctx context.Context, arg CreateCourtParams) (Court, error) {
	row := q.db.QueryRow(ctx, createCourt,
		arg.VenueID,
		arg.Name,
		arg.OpenHour,
		arg.CloseHour,
		arg.PricePerHour,
	)
	var i Court
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.OpenHour,
		&i.CloseHour,
		&i.PricePerHour,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
