// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stripe_event.sql

package postgres

import (
	"context"
)

const recordStripeEvent = `-- name: RecordStripeEvent :one
INSERT INTO stripe_events (id, type)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
RETURNING id
`

type RecordStripeEventParams struct {
	ID   string `json:"id"`
	Type string `json:"type"`
}

func (q *Queries) RecordStripeEvent(ctx context.Context, arg RecordStripeEventParams) (string, error) {
	row := q.db.QueryRow(ctx, recordStripeEvent, arg.ID, arg.Type)
	var id string
	err := row.Scan(&id)
	return id, err
}
