// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venue.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (
    owner_id, name, city, address
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, owner_id, name, city, address, is_active, created_at, updated_at
`

type CreateVenueParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Name    string    `json:"name"`
	City    string    `json:"city"`
	Address string    `json:"address"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.OwnerID,
		arg.Name,
		arg.City,
		arg.Address,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVenue = `-- name: DeactivateVenue :one
UPDATE venues
SET is_active = false
WHERE id = $1
RETURNING id, owner_id, name, city, address, is_active, created_at, updated_at
`

func (q *Queries) DeactivateVenue(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, deactivateVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenue = `-- name: GetVenue :one
SELECT id, owner_id, name, city, address, is_active, created_at, updated_at FROM venues
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVenue(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, owner_id, name, city, address, is_active, created_at, updated_at FROM venues
WHERE is_active
ORDER BY name
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.City,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET name    = $2,
    city    = $3,
    address = $4
WHERE id = $1
RETURNING id, owner_id, name, city, address, is_active, created_at, updated_at
`

type UpdateVenueParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	City    string    `json:"city"`
	Address string    `json:"address"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Address,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.City,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
