// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/thelong0705/deuce/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockBookingUsecase is an autogenerated mock type for the BookingUsecase type
type MockBookingUsecase struct {
	mock.Mock
}

type MockBookingUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingUsecase) EXPECT() *MockBookingUsecase_Expecter {
	return &MockBookingUsecase_Expecter{mock: &_m.Mock}
}

// Availability provides a mock function with given fields: ctx, courtID, day
func (_m *MockBookingUsecase) Availability(ctx context.Context, courtID uuid.UUID, day time.Time) ([]entity.Slot, error) {
	ret := _m.Called(ctx, courtID, day)

	if len(ret) == 0 {
		panic("no return value specified for Availability")
	}

	var r0 []entity.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]entity.Slot, error)); ok {
		return rf(ctx, courtID, day)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []entity.Slot); ok {
		r0 = rf(ctx, courtID, day)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = rf(ctx, courtID, day)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingUsecase_Availability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Availability'
type MockBookingUsecase_Availability_Call struct {
	*mock.Call
}

// Availability is a helper method to define mock.On call
//   - ctx context.Context
//   - courtID uuid.UUID
//   - day time.Time
func (_e *MockBookingUsecase_Expecter) Availability(ctx interface{}, courtID interface{}, day interface{}) *MockBookingUsecase_Availability_Call {
	return &MockBookingUsecase_Availability_Call{Call: _e.mock.On("Availability", ctx, courtID, day)}
}

func (_c *MockBookingUsecase_Availability_Call) Run(run func(ctx context.Context, courtID uuid.UUID, day time.Time)) *MockBookingUsecase_Availability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockBookingUsecase_Availability_Call) Return(_a0 []entity.Slot, _a1 error) *MockBookingUsecase_Availability_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingUsecase_Availability_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) ([]entity.Slot, error)) *MockBookingUsecase_Availability_Call {
	_c.Call.Return(run)
	return _c
}

// Book provides a mock function with given fields: ctx, in
func (_m *MockBookingUsecase) Book(ctx context.Context, in entity.BookSlotInput) (*entity.HeldBooking, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Book")
	}

	var r0 *entity.HeldBooking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.BookSlotInput) (*entity.HeldBooking, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.BookSlotInput) *entity.HeldBooking); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.HeldBooking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.BookSlotInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingUsecase_Book_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Book'
type MockBookingUsecase_Book_Call struct {
	*mock.Call
}

// Book is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.BookSlotInput
func (_e *MockBookingUsecase_Expecter) Book(ctx interface{}, in interface{}) *MockBookingUsecase_Book_Call {
	return &MockBookingUsecase_Book_Call{Call: _e.mock.On("Book", ctx, in)}
}

func (_c *MockBookingUsecase_Book_Call) Run(run func(ctx context.Context, in entity.BookSlotInput)) *MockBookingUsecase_Book_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.BookSlotInput))
	})
	return _c
}

func (_c *MockBookingUsecase_Book_Call) Return(_a0 *entity.HeldBooking, _a1 error) *MockBookingUsecase_Book_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingUsecase_Book_Call) RunAndReturn(run func(context.Context, entity.BookSlotInput) (*entity.HeldBooking, error)) *MockBookingUsecase_Book_Call {
	_c.Call.Return(run)
	return _c
}

// ListForPlayer provides a mock function with given fields: ctx, playerID
func (_m *MockBookingUsecase) ListForPlayer(ctx context.Context, playerID uuid.UUID) ([]entity.PlayerBooking, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for ListForPlayer")
	}

	var r0 []entity.PlayerBooking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.PlayerBooking, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.PlayerBooking); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlayerBooking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingUsecase_ListForPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForPlayer'
type MockBookingUsecase_ListForPlayer_Call struct {
	*mock.Call
}

// ListForPlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockBookingUsecase_Expecter) ListForPlayer(ctx interface{}, playerID interface{}) *MockBookingUsecase_ListForPlayer_Call {
	return &MockBookingUsecase_ListForPlayer_Call{Call: _e.mock.On("ListForPlayer", ctx, playerID)}
}

func (_c *MockBookingUsecase_ListForPlayer_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockBookingUsecase_ListForPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookingUsecase_ListForPlayer_Call) Return(_a0 []entity.PlayerBooking, _a1 error) *MockBookingUsecase_ListForPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingUsecase_ListForPlayer_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.PlayerBooking, error)) *MockBookingUsecase_ListForPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingUsecase creates a new instance of MockBookingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingUsecase {
	mock := &MockBookingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
