// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/thelong0705/deuce/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCityUsecase is an autogenerated mock type for the CityUsecase type
type MockCityUsecase struct {
	mock.Mock
}

type MockCityUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCityUsecase) EXPECT() *MockCityUsecase_Expecter {
	return &MockCityUsecase_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx
func (_m *MockCityUsecase) List(ctx context.Context) ([]entity.City, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.City, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.City); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCityUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCityUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCityUsecase_Expecter) List(ctx interface{}) *MockCityUsecase_List_Call {
	return &MockCityUsecase_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockCityUsecase_List_Call) Run(run func(ctx context.Context)) *MockCityUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCityUsecase_List_Call) Return(_a0 []entity.City, _a1 error) *MockCityUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCityUsecase_List_Call) RunAndReturn(run func(context.Context) ([]entity.City, error)) *MockCityUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCityUsecase creates a new instance of MockCityUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCityUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCityUsecase {
	mock := &MockCityUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
