// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/thelong0705/deuce/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCourtUsecase is an autogenerated mock type for the CourtUsecase type
type MockCourtUsecase struct {
	mock.Mock
}

type MockCourtUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourtUsecase) EXPECT() *MockCourtUsecase_Expecter {
	return &MockCourtUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockCourtUsecase) Create(ctx context.Context, in entity.CreateCourtInput) (*entity.Court, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Court
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateCourtInput) (*entity.Court, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateCourtInput) *entity.Court); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Court)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateCourtInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourtUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCourtUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.CreateCourtInput
func (_e *MockCourtUsecase_Expecter) Create(ctx interface{}, in interface{}) *MockCourtUsecase_Create_Call {
	return &MockCourtUsecase_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockCourtUsecase_Create_Call) Run(run func(ctx context.Context, in entity.CreateCourtInput)) *MockCourtUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CreateCourtInput))
	})
	return _c
}

func (_c *MockCourtUsecase_Create_Call) Return(_a0 *entity.Court, _a1 error) *MockCourtUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourtUsecase_Create_Call) RunAndReturn(run func(context.Context, entity.CreateCourtInput) (*entity.Court, error)) *MockCourtUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourtUsecase creates a new instance of MockCourtUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourtUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourtUsecase {
	mock := &MockCourtUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
