// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "github.com/thelong0705/deuce/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentWebhook is an autogenerated mock type for the PaymentWebhook type
type MockPaymentWebhook struct {
	mock.Mock
}

type MockPaymentWebhook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentWebhook) EXPECT() *MockPaymentWebhook_Expecter {
	return &MockPaymentWebhook_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: payload, signature
func (_m *MockPaymentWebhook) Verify(payload []byte, signature string) (*entity.PaymentEvent, error) {
	ret := _m.Called(payload, signature)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *entity.PaymentEvent
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string) (*entity.PaymentEvent, error)); ok {
		return rf(payload, signature)
	}
	if rf, ok := ret.Get(0).(func([]byte, string) *entity.PaymentEvent); ok {
		r0 = rf(payload, signature)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PaymentEvent)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = rf(payload, signature)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentWebhook_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPaymentWebhook_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - payload []byte
//   - signature string
func (_e *MockPaymentWebhook_Expecter) Verify(payload interface{}, signature interface{}) *MockPaymentWebhook_Verify_Call {
	return &MockPaymentWebhook_Verify_Call{Call: _e.mock.On("Verify", payload, signature)}
}

func (_c *MockPaymentWebhook_Verify_Call) Run(run func(payload []byte, signature string)) *MockPaymentWebhook_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentWebhook_Verify_Call) Return(_a0 *entity.PaymentEvent, _a1 error) *MockPaymentWebhook_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentWebhook_Verify_Call) RunAndReturn(run func([]byte, string) (*entity.PaymentEvent, error)) *MockPaymentWebhook_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentWebhook creates a new instance of MockPaymentWebhook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentWebhook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentWebhook {
	mock := &MockPaymentWebhook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
