// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/thelong0705/deuce/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockUserUsecase is an autogenerated mock type for the UserUsecase type
type MockUserUsecase struct {
	mock.Mock
}

type MockUserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUsecase) EXPECT() *MockUserUsecase_Expecter {
	return &MockUserUsecase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, token
func (_m *MockUserUsecase) Authenticate(ctx context.Context, token string) (*entity.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUsecase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockUserUsecase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockUserUsecase_Expecter) Authenticate(ctx interface{}, token interface{}) *MockUserUsecase_Authenticate_Call {
	return &MockUserUsecase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, token)}
}

func (_c *MockUserUsecase_Authenticate_Call) Run(run func(ctx context.Context, token string)) *MockUserUsecase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserUsecase_Authenticate_Call) Return(_a0 *entity.User, _a1 error) *MockUserUsecase_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUsecase_Authenticate_Call) RunAndReturn(run func(context.Context, string) (*entity.User, error)) *MockUserUsecase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, in
func (_m *MockUserUsecase) Login(ctx context.Context, in entity.LoginInput) (string, *entity.Session, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 *entity.Session
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.LoginInput) (string, *entity.Session, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.LoginInput) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.LoginInput) *entity.Session); ok {
		r1 = rf(ctx, in)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.Session)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.LoginInput) error); ok {
		r2 = rf(ctx, in)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.LoginInput
func (_e *MockUserUsecase_Expecter) Login(ctx interface{}, in interface{}) *MockUserUsecase_Login_Call {
	return &MockUserUsecase_Login_Call{Call: _e.mock.On("Login", ctx, in)}
}

func (_c *MockUserUsecase_Login_Call) Run(run func(ctx context.Context, in entity.LoginInput)) *MockUserUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.LoginInput))
	})
	return _c
}

func (_c *MockUserUsecase_Login_Call) Return(_a0 string, _a1 *entity.Session, _a2 error) *MockUserUsecase_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserUsecase_Login_Call) RunAndReturn(run func(context.Context, entity.LoginInput) (string, *entity.Session, error)) *MockUserUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, token
func (_m *MockUserUsecase) Logout(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserUsecase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockUserUsecase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockUserUsecase_Expecter) Logout(ctx interface{}, token interface{}) *MockUserUsecase_Logout_Call {
	return &MockUserUsecase_Logout_Call{Call: _e.mock.On("Logout", ctx, token)}
}

func (_c *MockUserUsecase_Logout_Call) Run(run func(ctx context.Context, token string)) *MockUserUsecase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserUsecase_Logout_Call) Return(_a0 error) *MockUserUsecase_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserUsecase_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockUserUsecase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in
func (_m *MockUserUsecase) Register(ctx context.Context, in entity.CreateUserInput) (*entity.User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateUserInput) (*entity.User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateUserInput) *entity.User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateUserInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.CreateUserInput
func (_e *MockUserUsecase_Expecter) Register(ctx interface{}, in interface{}) *MockUserUsecase_Register_Call {
	return &MockUserUsecase_Register_Call{Call: _e.mock.On("Register", ctx, in)}
}

func (_c *MockUserUsecase_Register_Call) Run(run func(ctx context.Context, in entity.CreateUserInput)) *MockUserUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CreateUserInput))
	})
	return _c
}

func (_c *MockUserUsecase_Register_Call) Return(_a0 *entity.User, _a1 error) *MockUserUsecase_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserUsecase_Register_Call) RunAndReturn(run func(context.Context, entity.CreateUserInput) (*entity.User, error)) *MockUserUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserUsecase creates a new instance of MockUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUsecase {
	mock := &MockUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
