// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/thelong0705/deuce/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRegister is an autogenerated mock type for the UserRegister type
type MockUserRegister struct {
	mock.Mock
}

type MockUserRegister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRegister) EXPECT() *MockUserRegister_Expecter {
	return &MockUserRegister_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: ctx, in
func (_m *MockUserRegister) Register(ctx context.Context, in entity.CreateUserInput) (*entity.User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateUserInput) (*entity.User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateUserInput) *entity.User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateUserInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRegister_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserRegister_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.CreateUserInput
func (_e *MockUserRegister_Expecter) Register(ctx interface{}, in interface{}) *MockUserRegister_Register_Call {
	return &MockUserRegister_Register_Call{Call: _e.mock.On("Register", ctx, in)}
}

func (_c *MockUserRegister_Register_Call) Run(run func(ctx context.Context, in entity.CreateUserInput)) *MockUserRegister_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CreateUserInput))
	})
	return _c
}

func (_c *MockUserRegister_Register_Call) Return(_a0 *entity.User, _a1 error) *MockUserRegister_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRegister_Register_Call) RunAndReturn(run func(context.Context, entity.CreateUserInput) (*entity.User, error)) *MockUserRegister_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRegister creates a new instance of MockUserRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRegister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRegister {
	mock := &MockUserRegister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
