// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/thelong0705/deuce/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockVenueUsecase is an autogenerated mock type for the VenueUsecase type
type MockVenueUsecase struct {
	mock.Mock
}

type MockVenueUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVenueUsecase) EXPECT() *MockVenueUsecase_Expecter {
	return &MockVenueUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockVenueUsecase) Create(ctx context.Context, in entity.CreateVenueInput) (*entity.Venue, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Venue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateVenueInput) (*entity.Venue, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CreateVenueInput) *entity.Venue); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Venue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CreateVenueInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVenueUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVenueUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in entity.CreateVenueInput
func (_e *MockVenueUsecase_Expecter) Create(ctx interface{}, in interface{}) *MockVenueUsecase_Create_Call {
	return &MockVenueUsecase_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockVenueUsecase_Create_Call) Run(run func(ctx context.Context, in entity.CreateVenueInput)) *MockVenueUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CreateVenueInput))
	})
	return _c
}

func (_c *MockVenueUsecase_Create_Call) Return(_a0 *entity.Venue, _a1 error) *MockVenueUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVenueUsecase_Create_Call) RunAndReturn(run func(context.Context, entity.CreateVenueInput) (*entity.Venue, error)) *MockVenueUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOwner provides a mock function with given fields: ctx, ownerID
func (_m *MockVenueUsecase) ListByOwner(ctx context.Context, ownerID uuid.UUID) ([]entity.Venue, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOwner")
	}

	var r0 []entity.Venue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Venue, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Venue); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Venue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVenueUsecase_ListByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwner'
type MockVenueUsecase_ListByOwner_Call struct {
	*mock.Call
}

// ListByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
func (_e *MockVenueUsecase_Expecter) ListByOwner(ctx interface{}, ownerID interface{}) *MockVenueUsecase_ListByOwner_Call {
	return &MockVenueUsecase_ListByOwner_Call{Call: _e.mock.On("ListByOwner", ctx, ownerID)}
}

func (_c *MockVenueUsecase_ListByOwner_Call) Run(run func(ctx context.Context, ownerID uuid.UUID)) *MockVenueUsecase_ListByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVenueUsecase_ListByOwner_Call) Return(_a0 []entity.Venue, _a1 error) *MockVenueUsecase_ListByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVenueUsecase_ListByOwner_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Venue, error)) *MockVenueUsecase_ListByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, city
func (_m *MockVenueUsecase) Search(ctx context.Context, city string) ([]entity.Venue, error) {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []entity.Venue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.Venue, error)); ok {
		return rf(ctx, city)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Venue); ok {
		r0 = rf(ctx, city)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Venue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVenueUsecase_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockVenueUsecase_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - city string
func (_e *MockVenueUsecase_Expecter) Search(ctx interface{}, city interface{}) *MockVenueUsecase_Search_Call {
	return &MockVenueUsecase_Search_Call{Call: _e.mock.On("Search", ctx, city)}
}

func (_c *MockVenueUsecase_Search_Call) Run(run func(ctx context.Context, city string)) *MockVenueUsecase_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVenueUsecase_Search_Call) Return(_a0 []entity.Venue, _a1 error) *MockVenueUsecase_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVenueUsecase_Search_Call) RunAndReturn(run func(context.Context, string) ([]entity.Venue, error)) *MockVenueUsecase_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVenueUsecase creates a new instance of MockVenueUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVenueUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVenueUsecase {
	mock := &MockVenueUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
